export {
  RoleManifestSchema,
  roleManifestList,
  roleManifests,
  getRoleManifest,
  type RoleManifest,
} from "../roles"

export {
  buildDirective,
  buildPrompt,
  buildPromptSections,
  buildReminder,
  executionPrompt,
  planningPrompt,
  type DirectiveOptions,
  type PromptContent,
  type PromptMetadata,
  type PromptModule,
  type PromptSection,
  type PromptSectionKind,
} from "../prompts"

export {
  createExtensionRegistry,
  CapabilityRequirementSchema,
  CommandDescriptorSchema,
  CommandSurfaceSchema,
  ExtensionDescriptorSchema,
  ExtensionKindSchema,
  HookDescriptorSchema,
  HookSurfaceSchema,
  SafetyMetadataSchema,
  ToolDescriptorSchema,
  ToolSurfaceSchema,
  exampleCommandDescriptor,
  exampleExtensionDescriptors,
  exampleHookDescriptor,
  exampleToolDescriptor,
  type CapabilityRequirement,
  type CommandDescriptor,
  type CommandSurface,
  type ExtensionDescriptor,
  type ExtensionKind,
  type ExtensionRegistry,
  type HookDescriptor,
  type HookSurface,
  type SafetyMetadata,
  type ToolDescriptor,
  type ToolSurface,
} from "../extensions"
